# Generated by Django 3.1.1 on 2020-11-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20201105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='name',
            field=models.CharField(default='fill in title', max_length=255),
            preserve_default=False,
        ),
    ]
