# Generated by Django 3.1.1 on 2020-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
