# Generated by Django 3.1.1 on 2020-12-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_connecteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connecteduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='app_one.user'),
        ),
    ]
